name: tests

on:
  pull_request: # Run on all pull requests
  push: # Run only on pushes to master
    branches:
      - master
  schedule: # Run monthly
    - cron: "0 0 1 * *"

jobs:
  test:
    name: ${{ matrix.os }} (${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.17.13", "1.18.5", "1.19.0"]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies Windows
        if: os.runner == 'Windows'
        run: |
          choco install make
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: make all
